# Generated by Django 2.2.6 on 2020-05-20 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='file_template',
            fields=[
                ('file_label', models.IntegerField(primary_key=True, serialize=False)),
                ('file_name', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='user_file',
            fields=[
                ('file_name', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('file_content', models.TextField()),
                ('file_label', models.IntegerField()),
            ],
        ),
    ]
